name: Build Unsigned IPA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: AniLiberty
      EXPORT_OPTIONS_PLIST: ExportOptions.plist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gems
        run: |
          sudo gem install xcpretty cocoapods

      - name: Determine project or workspace
        id: detect
        run: |
          ws=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n1)
          proj=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n1)

          if [ -n "$ws" ]; then
            echo "type=workspace" >> $GITHUB_OUTPUT
            echo "file=$(basename "$ws")" >> $GITHUB_OUTPUT
          elif [ -n "$proj" ]; then
            echo "type=project" >> $GITHUB_OUTPUT
            echo "file=$(basename "$proj")" >> $GITHUB_OUTPUT
          else
            echo "No Xcode project or workspace found!"
            exit 1
          fi
        shell: bash

      - name: Clean & Archive
        run: |
          mkdir -p build
          if [ "${{ steps.detect.outputs.type }}" = "workspace" ]; then
            xcodebuild clean archive \
              -workspace "${{ steps.detect.outputs.file }}" \
              -scheme "$SCHEME" \
              -archivePath "build/$SCHEME.xcarchive" | xcpretty
          else
            xcodebuild clean archive \
              -project "${{ steps.detect.outputs.file }}" \
              -scheme "$SCHEME" \
              -archivePath "build/$SCHEME.xcarchive" | xcpretty
        shell: bash

      - name: Export unsigned IPA
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath "build/$SCHEME.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "build/ipa" | xcpretty
        shell: bash

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: AniLiberty-unsigned
          path: build/ipa/*.ipa
          if-no-files-found: warn
