name: Build AniLiberty IPA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: AniLiberty
      EXPORT_OPTIONS_PLIST: ExportOptions.plist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gems
        run: |
          sudo gem install xcpretty cocoapods

      - name: Build Archive
        run: |
          mkdir -p build
          ws=$(ls *.xcworkspace 2>/dev/null | head -n1)
          proj=$(ls *.xcodeproj 2>/dev/null | head -n1)
      
          if [ -n "$ws" ]; then
            xcodebuild clean archive -workspace "$ws" -scheme "$SCHEME" -archivePath "build/$SCHEME.xcarchive" | xcpretty
          elif [ -n "$proj" ]; then
            xcodebuild clean archive -project "$proj" -scheme "$SCHEME" -archivePath "build/$SCHEME.xcarchive" | xcpretty
          else
            echo "No Xcode project or workspace found!"
            exit 1
          fi


      - name: Export unsigned IPA
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath "build/$SCHEME.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "build/ipa" | xcpretty

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: AniLiberty-unsigned
          path: build/ipa/*.ipa
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
