name: Build Unsigned IPA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: AniLiberty
      EXPORT_OPTIONS_PLIST: ExportOptions.plist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gems
        run: sudo gem install xcpretty cocoapods

      # Определяем workspace или project
      - name: Detect Xcode project/workspace
        id: detect
        run: |
          ws=$(ls *.xcworkspace 2>/dev/null | head -n1)
          proj=$(ls *.xcodeproj 2>/dev/null | head -n1)
          
          if [ -n "$ws" ]; then
            echo "TYPE=workspace" >> $GITHUB_ENV
            echo "FILE=$ws" >> $GITHUB_ENV
          elif [ -n "$proj" ]; then
            echo "TYPE=project" >> $GITHUB_ENV
            echo "FILE=$proj" >> $GITHUB_ENV
          else
            echo "No Xcode project or workspace found!"
            exit 1
          fi

      # Создаем папку build
      - name: Create build directory
        run: mkdir -p build

      # Архивируем проект
      - name: Archive Xcode project
        run: |
          if [ "$TYPE" = "workspace" ]; then
            xcodebuild clean archive \
              -workspace "$FILE" \
              -scheme "$SCHEME" \
              -archivePath "build/$SCHEME.xcarchive" | xcpretty
          else
            xcodebuild clean archive \
              -project "$FILE" \
              -scheme "$SCHEME" \
              -archivePath "build/$SCHEME.xcarchive" | xcpretty
          fi

      # Экспортируем unsigned IPA
      - name: Export unsigned IPA
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath "build/$SCHEME.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "build/ipa" | xcpretty

      # Загружаем IPA как артефакт
      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: AniLiberty-unsigned
          path: build/ipa/*.ipa
          if-no-files-found: warn
