name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # ← добавляет кнопку "Run workflow" в Actions

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby for CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # версия Ruby для Cocoapods

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install --repo-update

    - name: Set up Xcode
      uses: actions/setup-xcode@v4
      with:
        xcode-version: '16.4'

    - name: Install Swift Packages
      run: xcodebuild -resolvePackageDependencies -project Anilibria.xcodeproj

    - name: Build and archive
      run: |
        xcodebuild archive \
          -project Anilibria.xcodeproj \
          -scheme AniLiberty \
          -configuration Release \
          -archivePath ${{ github.workspace }}/build/AniLiberty.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ${{ github.workspace }}/build/AniLiberty.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath ${{ github.workspace }}/build

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v4
      with:
        name: AniLiberty-unsigned
        path: build/*.ipa
